package com.upgrad.quora.service.entity;

import java.io.Serializable;
import java.time.ZonedDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

//@Entity annotation defining that this class should be implemented as table in the db
//@Table annotation giving the name and scheme for the entity in the db
//@NamedQueries annotation defines queries which will be executed on this entity to help the corresponding dao

@Entity
@Table(name = "question")
@NamedQueries(
    {
        @NamedQuery(name = "allQuestionsByUserId", query = "select q from QuestionEntity q where q.id = :id"),
        @NamedQuery(name = "questionByQUuid", query = "select q from QuestionEntity q where q.uuid =:uuid"),
        @NamedQuery(name = "allQuestions", query = "select q from QuestionEntity q")
    }
)
public class QuestionEntity implements Serializable {

  //attributes of this class which will be represented as columns in the corresponding table in the db
  //@ID annotation marks the id attribute as the primary key
  //@Column annotation gives the name to be given to the corresponding column in the db
  //@GeneratedValue annotation implies that this field is autogenerated
  //@Size annotation defines the size limit the value can have
  //@NotNull annotation marks that the attribute is mandatory
  //@ManyToOne Annotation defines the association between two entities
  //@OnDelete Annotation defines the cascading nature of the delete operation when entities are associated thru attributes
  //@JoinColumn Annotation defines the column that joins two entities and the name for that column


  @Id
  @Column(name = "id")
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;

  @Column(name = "uuid")
  @NotNull
  @Size(max = 200)
  private String uuid;


  @Column(name = "content")
  @NotNull
  @Size(max = 500)
  private String content;

  @Column(name = "date")
  @NotNull
  private ZonedDateTime date;

  @ManyToOne
  @JoinColumn(name = "user_id")
  @OnDelete(action = OnDeleteAction.CASCADE)
  @NotNull
  private UserEntity userEntity;

  //getters and setters for all the attributes of the class

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public ZonedDateTime getDate() {
    return date;
  }

  public void setDate(ZonedDateTime date) {
    this.date = date;
  }

  public UserEntity getUserEntity() {
    return userEntity;
  }

  public void setUserEntity(UserEntity userEntity) {
    this.userEntity = userEntity;
  }

  @Override
  public boolean equals(Object obj) {
    return new EqualsBuilder().append(this, obj).isEquals();
  }

  @Override
  public int hashCode() {
    return new HashCodeBuilder().append(this).hashCode();
  }

  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, ToStringStyle.MULTI_LINE_STYLE);
  }
}
